import {extraPages, metadata, enhance} from './seo-content.mjs';
import {seoHead, optimizeImages, writeDiscovery} from './seo.mjs';
import {pages, products} from './content.mjs';
import { mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const dist=path.join(root,'dist');
const team=JSON.parse(readFileSync(path.join(root,'team.json'),'utf8'));
const escapeHtml=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const teamSection=team.length?`<section class="section team-section"><h2>Our team.</h2><div class="team-grid">${team.map(person=>`<article><img src="${escapeHtml(person.photo)}" alt="${escapeHtml(person.name)}" loading="lazy" width="1080" height="1440"><h3>${escapeHtml(person.name)}</h3><p>${escapeHtml(person.position)}</p>${person.linkedin?`<a href="${escapeHtml(person.linkedin)}" aria-label="${escapeHtml(person.name)} on LinkedIn" target="_blank" rel="noopener noreferrer">LinkedIn ↗</a>`:''}</article>`).join('')}</div></section>`:'';
const brand=`<img class="brand-symbol" src="/assets/brand-symbol.png" alt=""><img class="brand-name" src="/assets/brand-wordmark.svg" alt="NeoNaar Biotech">`;
const header=`<a class="skip" href="#main">Skip to content</a><header class="header"><a class="brand" href="/" aria-label="NeoNaar Biotech home">${brand}</a><button class="menu-toggle" aria-expanded="false" aria-controls="site-menu" aria-label="Open menu"><span></span><span></span></button><nav id="site-menu" aria-label="Main navigation" hidden><a href="/">Home</a><a href="/about/">About</a><a href="/products/">Products</a><a href="/microfibrillated-cellulose/">Microfibrillated Cellulose</a><a href="/applications/personal-care/">Personal Care</a><a href="/applications/coatings/">Coatings</a><a href="/applications/packaging/">Packaging</a><a href="/contact/">Contact</a></nav></header>`;
const footer=`<footer><div class="footer-main"><div class="footer-brand"><a class="brand" href="/" aria-label="NeoNaar Biotech home">${brand}</a><p>Functional materials.<br>Biological origins.</p></div><div><a href="/about/">About</a><a href="/products/">Products</a><a href="/contact/">Contact</a></div><div><a href="mailto:hello@neonaar.com">hello@neonaar.com</a><p>Coimbatore, India</p></div></div><div class="footer-bottom"><span>© 2026 NeoNaar Biotech Private Limited</span><a href="/credits.html">Photography &amp; film credits</a></div></footer>`;
const arc=`<svg class="arc-divider" viewBox="0 0 400 32" aria-hidden="true"><path d="M0 16H132C154 16 158 3 177 3C195 3 205 29 223 29C242 29 246 16 268 16H400M0 22H132C154 22 158 9 177 9C195 9 205 23 223 23C242 23 246 10 268 10H400"/></svg>`;
const builtRoutes=[];
function page(route,title,description,content,home=false){
 route=route==='products/neocell/pure'?'products/neocell-pure':route;
 [title,description]=metadata[route]||[title,description];
 content=enhance(route,content).replace(/<h2><\/h2>/g,'<h2>Material platforms</h2>');
 content=content.replace(/<img\b[^>]*>/,tag=>tag.replace('loading="lazy"','loading="eager" fetchpriority="high"'));
 builtRoutes.push(route);
 const folder=route.endsWith('.html')?dist:path.join(dist,route);mkdirSync(folder,{recursive:true});
 const body=route==='contact'?content.replace('<section class="section contact-layout">',teamSection+'<section class="section contact-layout">'):content;
 writeFileSync(route.endsWith('.html')?path.join(dist,route):path.join(folder,'index.html'),optimizeImages(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(title.includes(' | ')?title:title+' | NeoNaar Biotech')}</title><meta name="description" content="${escapeHtml(description)}"><meta name="theme-color" content="#2d4a2b"><link rel="icon" href="/assets/brand-symbol.png"><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/editorial.css"><link rel="stylesheet" href="/assets/fonts/google-fonts.css"><link rel="stylesheet" href="/visual.css">${seoHead(route,title,description)}${home?'<link rel="preload" as="image" href="/assets/kerala-palakkad-paddy-28901908-1200.webp" fetchpriority="high">':''}<link rel="stylesheet" href="/seo.css"></head><body class="${home?'home':'inner-page'}">${header}<main id="main">${body}</main>${footer}<script src="/app.js" defer></script></body></html>`,root));
}
for(const entry of [...pages,...extraPages])page(entry.route,entry.title,entry.description,entry.content,entry.route==='');
const items=products;
const form=`<form id="enquiry-form"><h2>Start a conversation.</h2><div class="form-grid"><label>Name<input name="Name" autocomplete="name" required maxlength="100"></label><label>Company<input name="Company" autocomplete="organization" required maxlength="150"></label><label>Work email<input name="Email" type="email" autocomplete="email" required maxlength="150"></label><label>Country<input name="Country" required autocomplete="country-name" maxlength="100"></label><label>Industry<select name="Industry"><option value="">Select industry</option>${['Personal care','Agriculture','Coatings','Packaging & material systems','Other'].map(x=>`<option>${x}</option>`).join('')}</select></label><label>Material of interest<select name="Material" id="material-select"><option value="">Help me choose</option>${Object.values(items).map(p=>`<option>${p.name}</option>`).join('')}</select></label><label>Enquiry type<select name="Request" id="request-select"><option value="">General enquiry</option>${['Request a Sample','Request Technical Data','Discuss Your Formulation','Talk to NeoNaar','Request Sample','Request Pricing','Request Technical Callback','Request Formulation Callback','Discuss Target Profile','Request Callback'].map(x=>`<option>${x}</option>`).join('')}</select></label><label>Application<input name="Application" required maxlength="200" placeholder="What are you developing?"></label><label>Estimated material requirement (optional)<input name="Quantity" maxlength="100" placeholder="e.g. Evaluation sample"></label><label class="full">What are you trying to formulate?<textarea name="Message" required rows="4" maxlength="2000" placeholder="What would you like the material to do?"></textarea></label></div><button class="pill" type="submit">Prepare enquiry email <span aria-hidden="true">↗</span></button><p class="small-note">Opens a draft in your email app. Review and send it to complete your enquiry.</p><p id="form-status" role="status" hidden></p><a id="email-fallback" class="text-link" hidden>Open email draft again ↗</a></form>`;
page('contact','Contact Us','Contact NeoNaar for material samples, formulation discussions and commercial enquiries.',`<section class="page-intro centered"><h1>Let’s work on<br><em>the material.</em></h1><p>For samples, formulation evaluation and new possibilities.</p></section><section class="section contact-layout"><div class="contact-details">${arc}<h2>Talk to our team.</h2><p>Tell us what you are trying to structure, suspend, coat or formulate.</p><a href="mailto:hello@neonaar.com">hello@neonaar.com ↗</a><p>Technical &amp; formulation enquiries<br><a href="mailto:gm@neonaar.com">gm@neonaar.com ↗</a></p><p>NeoNaar Biotech Private Limited<br>Coimbatore, India</p></div>${form}</section>`);
const credits=readFileSync(path.join(root,'scripts/credits-content.html'),'utf8');
page('credits.html',...metadata['credits.html'].slice(0,2),credits);
writeDiscovery(builtRoutes,dist);
console.log('Generated '+builtRoutes.length+' canonical NeoNaar pages.');


