const a=(text,url)=>`<a class="text-link" href="${url}">${text} ↗</a>`;
const cta=(label='Request a Sample',industry='')=>a(label,`/contact/?material=NeoCell%20PURE&request=${encodeURIComponent(label)}&industry=${encodeURIComponent(industry)}`);
const sec=(title,body)=>`<section class="section editorial"><h2>${title}</h2>${body}</section>`;
const cards=items=>`<div class="function-grid">${items.map(([h,p])=>`<article><h3>${h}</h3><p>${p}</p></article>`).join('')}</div>`;
const faq=items=>sec('Buyer questions',`<div class="seo-faq">${items.map(([q,v])=>`<details><summary>${q}</summary><p>${v}</p></details>`).join('')}</div>`);
const hero=(title,copy,img)=>`<section class="category-hero seo-hero"><div><h1>${title}</h1><p>${copy}</p>${cta()}</div><img src="/assets/${img}" alt="${title}" fetchpriority="high"></section>`;
const commonFaq=[['What format does NeoNaar supply?','NeoCell PURE is presented as an aqueous gel / dispersion. Request the current technical data and confirm sample availability, solids content, packaging and storage guidance directly with NeoNaar.'],['Where is NeoNaar based?','NeoNaar Biotech Private Limited is based in Coimbatore, India.'],['How can companies evaluate NeoCell PURE?','Share your application, target behaviour and material requirement through the enquiry form. The team can discuss a sample and the technical information available for your evaluation.']];
export const extraPages=[
{route:'microfibrillated-cellulose',title:'Microfibrillated Cellulose (MFC) India | NeoNaar',description:'Explore microfibrillated cellulose for rheology, suspension and texture. Discuss NeoNaar’s MFC development, aqueous formats, technical data and samples in India.',keywords:['microfibrillated cellulose supplier India','MFC manufacturer India','cellulose rheology modifier','functional cellulose ingredient'],content:hero('Microfibrillated Cellulose for Formulation Development','Microfibrillated cellulose (MFC) is cellulose with a fine fibrillar structure. In water, interacting fibrils can form a physical network that influences flow, suspension and texture.','mfc-microscopy.svg')+sec('Bio-Based Rheology and Suspension Solutions',cards([['Rheology','A fibril network can provide structure at rest and flow more readily under shear. Behaviour depends on concentration, dispersion and the surrounding formulation.'],['Suspension','Network structure can help resist particle settling. Particle properties, storage conditions and the finished formula determine the result.'],['Water interaction','MFC is dispersed rather than dissolved in water. Its interaction with water and other ingredients contributes to the behaviour of the overall system.']]))+sec('Evaluate a functional cellulose ingredient',`<p>For teams comparing an MFC supplier in India or a cellulose rheology modifier, NeoNaar offers a development conversation around the NeoCell platform. NeoCell PURE focuses on personal care; NeoCell GROW focuses on agricultural formulation evaluation. Confirm current supply capability and specifications with the team.</p><div class="actions">${a('Evaluate NeoCell PURE','/products/neocell-pure/')}${a('Explore NeoCell GROW','/products/neocell/grow/')}${cta('Request Technical Data')}</div>`)+sec('Applications for microfibrillated cellulose',cards([['Personal care',a('Cellulose for personal care formulations','/applications/personal-care/')],['Coatings',a('MFC in water-based coatings','/applications/coatings/')],['Packaging',a('Emerging cellulose packaging applications','/applications/packaging/')]]))+faq([['What is microfibrillated cellulose?','MFC is a fibrillar form of cellulose. It is distinct from dissolved cellulose derivatives and from particulate microcrystalline cellulose.'],['What is MFC used for?','MFC is investigated for rheology, particle suspension, texture and material structure. Suitability depends on the particular grade and application.'],['How is MFC different from conventional cellulose thickeners?','Many conventional cellulose thickeners are soluble derivatives. MFC instead forms a dispersed fibril network; comparisons should consider flow, recovery and suspension, not just a single viscosity value.'],...commonFaq])},
{route:'applications/personal-care',title:'MFC for Personal Care & Cosmetics | NeoNaar',description:'Evaluate NeoCell PURE as a functional cellulose ingredient for cosmetic rheology, suspension and texture in creams, lotions, serums, gels and cleansing systems.',keywords:['MFC for cosmetics','rheology modifier for cosmetics','cellulose ingredient for personal care','suspension agent for cosmetics'],content:hero('Functional Cellulose for Personal Care & Cosmetics','Explore NeoCell PURE as a microfibrillated cellulose ingredient for formulation evaluation. Start with the behaviour your product needs, then test the complete formula.','personal-care.jpg')+sec('Formulation categories to explore',cards([['Creams & lotions','Compare structure, spread and recovery when screening a cellulose rheology modifier for creams and lotions.'],['Serums & gels','Evaluate texture and particle distribution. Check appearance and sensory requirements in the intended formulation.'],['Cleansers & shampoos','Assess flow and suspension alongside surfactants, electrolytes and your preservation system.'],['Suspensions','Study settling, redispersibility and storage behaviour for the selected particles and formula.']]))+sec('Selecting a rheology or suspension ingredient',`<p>Teams searching for a natural thickener, bio-based cosmetic ingredient or cosmetic suspension agent need more than a viscosity comparison. Evaluate dispersion, compatibility, sensory properties and stability under relevant conditions. Plant origin alone does not establish safety, regulatory status or finished-product performance.</p><p>NeoCell PURE is under development for personal-care-focused evaluation. No universal compatibility, dosage or regulatory approval is implied.</p><div class="actions">${a('Evaluate NeoCell PURE','/products/neocell-pure/')}${cta('Discuss Your Formulation','Personal care')}</div>`)+faq([['Can MFC be used in cosmetic formulations?','MFC can be considered for formulation development. A specific ingredient grade and finished product require appropriate safety, regulatory, compatibility and stability assessment before commercial use.'],['Can MFC help suspend particles?','A suitable fibril network can support suspension, but the outcome must be measured with the actual particles and formulation.'],...commonFaq.slice(0,1)])},
{route:'applications/coatings',title:'MFC for Water-Based Coatings | NeoNaar',description:'Explore microfibrillated cellulose as a bio-based coating additive for rheology and suspension evaluation in water-based coatings. Discuss technical requirements.',keywords:['MFC for coatings','cellulose rheology modifier coatings','bio based coating additive','cellulose for water based coatings'],content:hero('Microfibrillated Cellulose for Coatings','An application area for evaluating cellulose-based rheology, flow and suspension in water-based coating systems.','car-spray-painting-booth.jpg')+sec('Define the coating behaviour you need',cards([['Flow during application','Compare application viscosity, shear response and recovery with the existing binder system.'],['Pigment suspension','Measure settling and redispersibility with your pigment loading and storage conditions.'],['Finished-film properties','Check appearance, adhesion, water response and other relevant film properties. Do not infer them from wet-state rheology.']]))+sec('Development and evaluation status',`<p>NeoNaar is exploring MFC for coatings as a development application. A cellulose rheology modifier or bio-based coating additive must be evaluated with the actual binder, dispersants and pigments. This page does not represent a validated coating grade or a performance specification.</p><div class="actions">${a('Understand microfibrillated cellulose','/microfibrillated-cellulose/')}${cta('Discuss Your Formulation','Coatings')}${cta('Request Technical Data','Coatings')}</div>`)+faq([['Is NeoNaar MFC validated for my coating?','Not by this page. Share your coating system and target properties so the team can discuss the evidence available and an appropriate evaluation.']])},
{route:'applications/packaging',title:'Cellulose Materials for Packaging Research | NeoNaar',description:'Explore MFC packaging and cellulose-based coating research with NeoNaar. An emerging application area requiring barrier, process and end-of-life validation.',keywords:['MFC packaging','cellulose barrier material','cellulose based functional materials'],content:hero('Cellulose-Based Materials for Packaging Research','Packaging is an emerging application area for NeoNaar’s functional cellulose platform, not a commercially validated packaging product.','sustainable-cardboard-packaging.jpg')+sec('Questions for packaging development',cards([['Coatings & interfaces','Explore how a cellulose-containing layer interacts with the substrate and other components.'],['Barrier evaluation','Measure the relevant gas, moisture or grease barrier under intended humidity and use conditions. No barrier rating is claimed.'],['Processing & end of life','Assess coating, drying, converting and the complete packaging structure. Recycling, compostability and biodegradability need separate evidence.']]))+sec('Discuss an exploratory evaluation',`<p>For teams researching MFC packaging or a cellulose barrier material, the starting point is a clear substrate, process and performance brief. NeoNaar does not claim food-contact approval or validated end-of-life performance for these concepts.</p><div class="actions">${a('Explore the NeoCell platform','/products/neocell/')}${cta('Talk to NeoNaar','Packaging & material systems')}</div>`)+faq([['Is this a finished packaging material?','No. This is an emerging research and evaluation area. Finished-package performance and compliance have not been established by the information on this page.']])}
];
extraPages.push({route:'applications',title:'Biomaterial Applications | NeoNaar',description:'Explore NeoNaar cellulose material evaluation for personal care, coatings, agriculture and emerging packaging research. Find the relevant product and application page.',keywords:['functional biomaterial applications'],content:hero('Biomaterial Applications','Find the application closest to your formulation challenge. Each area has different evaluation requirements; a material’s origin alone does not establish performance in a finished product.','neocell-pure.png')+sec('Choose your application',cards([['Personal care and cosmetics','Explore rheology, texture and particle suspension for creams, lotions, serums and cleansing systems. Compare the intended sensory profile and stability requirements with the information available for NeoCell PURE. '+a('Personal care applications','/applications/personal-care/')],['Water-based coatings','Start with the binder, pigment system and application method. The coatings page explains development questions for flow, settling and finished-film properties; it does not claim a validated coating grade. '+a('Coatings evaluation','/applications/coatings/')],['Agricultural formulations','Consider physical suspension, seed-coating structure and handling behaviour with NeoCell GROW. Where the starting matrix itself needs a nutrient profile, explore the separate NeoNilam platform. '+a('NeoCell GROW','/products/neocell/grow/')+' '+a('NeoNilam materials','/products/neonilam/')],['Packaging research','Review cellulose-containing coatings and interfaces as an emerging research area. Substrate, humidity, converting conditions and the full material structure determine what needs to be measured. '+a('Packaging research','/applications/packaging/')]]))+sec('Prepare an evaluation brief','<p>Tell NeoNaar which formulation or substrate you use, what behaviour needs to improve, how the material will be applied and which evidence you need to make a procurement decision. Sample availability and relevant technical information can then be discussed against that brief.</p>'+a('Understand microfibrillated cellulose','/microfibrillated-cellulose/')+' '+cta('Discuss Your Formulation'))});
export const metadata={
 '':['NeoNaar | Microfibrillated Cellulose & Biomaterials India','NeoNaar develops microfibrillated cellulose (MFC) and functional biomaterials from agricultural residues for personal care, coatings, formulations and advanced material applications.',['microfibrillated cellulose India','bio based functional materials','cellulose biomaterial']],
 'about':['About NeoNaar Biotech | Biomaterials Company India','NeoNaar Biotech Private Limited is an Indian biomaterials company developing functional cellulose materials from agricultural residues in Coimbatore.',['NeoNaar Biotech','biomaterials company India','cellulose biomaterials India']],
 'products':['Functional Biomaterials: NeoCell & NeoNilam | NeoNaar','Compare NeoCell microfibrillated cellulose and NeoNilam nutrient-liquid platforms for personal care, agricultural and industrial formulation evaluation.',['functional cellulose ingredient','bio based material supplier India']],
 'products/neocell':['NeoCell MFC Material Platform | NeoNaar','Discover NeoCell, NeoNaar’s microfibrillated cellulose platform for rheology, suspension and texture evaluation in personal care and agricultural formulations.',['cellulose rheology modifier','cellulose suspension agent','plant based rheology modifier']],
 'products/neocell-pure':['NeoCell PURE: MFC for Personal Care | NeoNaar','Evaluate NeoCell PURE microfibrillated cellulose for personal-care rheology, suspension and texture. Request samples and current technical data from NeoNaar.',['MFC for cosmetics','natural rheology modifier','cellulose thickener for cosmetics','cosmetic suspension agent']],
 'products/neocell/grow':['NeoCell GROW for Agricultural Formulations | NeoNaar','Explore NeoCell GROW for agricultural suspension, seed-coating and carrier-system evaluation. Discuss samples and your formulation requirements.',['cellulose suspension agent agriculture','MFC seed coating']],
 'products/neonilam':['NeoNilam Nutrient-Liquid Platform | NeoNaar','Explore NeoNilam BASE and BALANCE, plant-derived nutrient-liquid starting materials for agricultural-input manufacturers and formulation development.',['plant derived nutrient liquid','agricultural formulation base']],
 'products/neonilam/base':['NeoNilam BASE Agricultural Formulation Base | NeoNaar','NeoNilam BASE is a plant-derived nutrient-liquid matrix for agricultural-input development. Discuss nutrient profiles, compatibility and sample evaluation.',['nutrient liquid formulation base']],
 'products/neonilam/balance':['NeoNilam BALANCE Nutrient-Liquid Development | NeoNaar','Explore NeoNilam BALANCE for an agreed nutrient starting profile in B2B agricultural-input development. Discuss your target profile with NeoNaar.',['nutrient formulation development']],
 'contact':['Request Samples & Technical Data | NeoNaar India','Contact NeoNaar in Coimbatore, India for MFC samples, technical data, supply enquiries and personal-care, coatings or agricultural formulation discussions.',['MFC supplier India','cellulose ingredient supplier India','request MFC sample']],
 'credits.html':['Photography & Film Credits | NeoNaar','Image, film, map and typography credits for the NeoNaar Biotech website, including licenses and identification of illustrative stock imagery.',[]]
};
export function enhance(route,html){
 if(route===''){
 html=html.replace('<h1>The Future','<div class="brand-headline">The Future').replace('</span></h1>','</span></div>');
 const intro=`<section class="section editorial seo-intro"><h1>Microfibrillated Cellulose &amp; Functional Biomaterials from Agricultural Residues</h1><p>NeoNaar develops performance-driven cellulose materials for formulators, manufacturers and material innovators seeking renewable alternatives for rheology, suspension, texture and material engineering.</p><div class="actions">${a('Explore microfibrillated cellulose','/microfibrillated-cellulose/')}${a('Evaluate NeoCell PURE','/products/neocell-pure/')}</div></section>`;
 html=html.replace('</button></section>','</button></section>'+intro).replace('Materials built<br><em>around function.</em>','Microfibrillated Cellulose for High-Performance Formulations').replace('The raw material<br>is only <em>the beginning.</em>','From Agricultural Residues to Functional Materials').replace('Performance is where<br><em>the material earns its place.</em>','Applications Across Personal Care, Coatings &amp; Advanced Materials');
 html=html.replace('<h2>Applications Across Personal Care, Coatings &amp; Advanced Materials</h2>','<h2><a href="/applications/">Applications Across Personal Care, Coatings &amp; Advanced Materials</a></h2>');
 html+=sec('Functional Cellulose for Personal Care &amp; Cosmetics',`<p>NeoCell PURE is the personal-care-focused functional cellulose product within the NeoCell platform. Evaluate texture, rheology and suspension in your intended formulation.</p>${a('Cellulose ingredients for personal care','/applications/personal-care/')}`)+sec('Bio-Based Rheology and Suspension Solutions',`<p>MFC forms a physical network in water. Explore structure, flow and recovery together when screening a cellulose rheology modifier.</p>${a('How microfibrillated cellulose functions','/microfibrillated-cellulose/')}`)+sec('Why NeoNaar',cards([['Application-led development','Discuss the formulation behaviour you need and the evidence required to evaluate it.'],['Based in India','NeoNaar Biotech Private Limited develops functional biomaterials in Coimbatore, India.']])+cta('Talk to NeoNaar'));
 }
 if(route==='about')html=html.replace('NeoNaar is building a biomaterials platform around agricultural residues, recovering useful fractions and developing them for industrial use.','NeoNaar Biotech Private Limited is an Indian biomaterials company developing functional cellulose materials from agricultural residues. NeoNaar is our company and brand; NeoCell is our cellulose material platform.');
 if(route==='products/neocell-pure'){
 html=html.replace('<h1 class="product-name">NeoCell PURE</h1>','<h1 class="product-name seo-product-title">NeoCell PURE <span>— Microfibrillated Cellulose for Personal Care Formulations</span></h1>').replace('using fibrillated cellulose.','using microfibrillated cellulose (MFC).').replace('<h2>Functionalities</h2>','<h2>What it solves</h2>').replace('<h2>Product properties</h2>','<h2>Material characteristics</h2>').replace('<h2>Applications</h2>','<h2>Formulation applications</h2>').replace('<h2>Current testing supports</h2>','<h2>Technical data</h2>');
 html+=sec('How it functions',`<p>Dispersed cellulose fibrils interact to form a physical network in water. Evaluate how the network responds at rest, under shear and after shear in the finished formulation.</p>${a('Understand MFC rheology','/microfibrillated-cellulose/')}`)+sec('Who should evaluate it',`<p>Formulation scientists, personal-care manufacturers, R&amp;D teams and ingredient distributors comparing cellulose rheology modifiers, thickeners or suspension ingredients can discuss an evaluation with NeoNaar.</p><p>Request the current technical data for sample-specific characteristics and available testing. No numerical specification, compatibility range, safety approval or supply commitment is implied here.</p><div class="actions">${a('Personal care formulation applications','/applications/personal-care/')}${cta('Request Technical Data')}</div>`)+sec('Request a sample',`<p>Tell us your application, target behaviour and estimated material requirement.</p>${cta()}`)+faq([['Can microfibrillated cellulose modify rheology?','MFC networks can change flow and recovery behaviour. NeoCell PURE should be compared in the intended formula, with results assessed under relevant storage and application conditions.'],...commonFaq]);
 }
 html=html.replaceAll('/products/neocell/pure/','/products/neocell-pure/').replace('<li>Biodegradable</li>','<li>Material research</li>');
 html=html.replace(/href="\/contact\/\?industry=Personal%20care"/g,'href="/applications/personal-care/"').replace(/href="\/contact\/\?industry=Coatings"/g,'href="/applications/coatings/"').replace(/href="\/contact\/\?industry=Packaging%20%26%20material%20systems"/g,'href="/applications/packaging/"');
 return html;
}
